id: lights_page
widgets:
  - obj:
      id: lights_page_card
      width: 440
      height: 360
      y: 40
      align: TOP_MID
      radius: 20
      bg_color: 0x1e293b
      border_width: 1
      border_color: 0x334155
      pad_all: 12
      scrollable: false
      scrollbar_mode: "OFF"
      layout:
        type: GRID
        grid_columns: [FR(1), FR(1)]
        grid_rows: [FR(1), FR(1)]
      widgets:
        - button:
            grid_cell_column_pos: 0
            grid_cell_row_pos: 0
            radius: 18
            bg_color: 0x334155
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: ${light_1_entity}
            widgets:
              - label:
                  align: CENTER
                  text: "Dining"
        - button:
            grid_cell_column_pos: 1
            grid_cell_row_pos: 0
            radius: 18
            bg_color: 0x334155
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: ${light_2_entity}
            widgets:
              - label:
                  align: CENTER
                  text: "Sofa"
        - button:
            grid_cell_column_pos: 0
            grid_cell_row_pos: 1
            radius: 18
            bg_color: 0x334155
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: ${light_3_entity}
            widgets:
              - label:
                  align: CENTER
                  text: "Wall"
        - button:
            grid_cell_column_pos: 1
            grid_cell_row_pos: 1
            radius: 18
            bg_color: 0x334155
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: ${light_4_entity}
            widgets:
              - label:
                  align: CENTER
                  text: "TV"
