wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"
api_encryption_key: "Zf8n4w6K4w1g2v0h8f21r7H8y8uV7FJQp3lD4o0hQ2k="
ota_password: "CHANGE_ME"
display_key: "Zf8n4w6K4w1g2v0h8f21r7H8y8uV7FJQp3lD4o0hQ2k="
display_ota: "CHANGE_ME"
